### ISSUE TITLE
get_libfply.sh not working

### ISSUE THREAD

**Issue by ericxtang** [tzwenn/PyOpenAirMirror#10]
Mirroring360 doesn't contain fply.dylib anymore.

**Comment by tzwenn** [comment]
Oh dear, I feared that would happen some day.
Although (or since) I suspect Mirroring360 (like Reflector, AirServer, etc.) to not have legally acquired the obfuscated binary blob they share in the first place, I feel very uncomfortably publicly sharing my local copy.

Do you have proposals on how to handle this?
For the time being I suppose using `fplyServer.py` with @espes [arm emulation](https://github.com/espes/Slave-in-the-Magic-Mirror) is a way to try it.

**Comment by plitewaikato** [comment]
The Wayback Machine at Internet Archive is your friend here.  :)
